server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: tb-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/1911?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis:
  configuration:
    map-underscore-to-camel-case: true  #═Нит├Ч├ч
  #mapper-locations:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
